version: "3.7"

services:
  validator1:
    image: hyperledger/besu:22.10.3
    restart: unless-stopped
    container_name: validator1
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys/validator1/key:/opt/besu/key
    network_mode: "host"
    env_file:
      - ./common.env
      - ./bootnodes.env
    environment:
      - BESU_IDENTITY=validator1
      - BESU_MINER_EXTRA_DATA=0x76616c696461746f7231
      - BESU_P2P_PORT=30301
      - BESU_RPC_HTTP_API=ADMIN,DEBUG,ETH,NET,PERM,PLUGINS,QBFT,TRACE,TXPOOL,WEB3
      - BESU_RPC_HTTP_AUTHENTICATION_ENABLED=false
      - BESU_RPC_HTTP_CORS_ORIGINS=all
      - BESU_RPC_HTTP_ENABLED=true
      - BESU_RPC_HTTP_HOST=0.0.0.0
      - BESU_RPC_HTTP_MAX_ACTIVE_CONNECTIONS=100
      - BESU_RPC_HTTP_PORT=8545
      - BESU_RPC_WS_API=ADMIN,DEBUG,ETH,NET,PERM,PLUGINS,QBFT,TRACE,TXPOOL,WEB3
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_ENABLED=true
      - BESU_RPC_WS_HOST=0.0.0.0
      - BESU_RPC_WS_MAX_ACTIVE_CONNECTIONS=100
      - BESU_RPC_WS_PORT=8546

  validator2:
    image: hyperledger/besu:22.10.3
    restart: unless-stopped
    container_name: validator2
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys/validator2/key:/opt/besu/key
    network_mode: "host"
    env_file:
      - ./common.env
      - ./bootnodes.env
    environment:
      - BESU_IDENTITY=validator2
      - BESU_MINER_EXTRA_DATA=0x76616c696461746f7232
      - BESU_P2P_PORT=30302

  validator3:
    image: hyperledger/besu:22.10.3
    restart: unless-stopped
    container_name: validator3
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys/validator3/key:/opt/besu/key
    network_mode: "host"
    env_file:
      - ./common.env
      - ./bootnodes.env
    environment:
      - BESU_IDENTITY=validator3
      - BESU_MINER_EXTRA_DATA=0x76616c696461746f7233
      - BESU_P2P_PORT=30303

  validator4:
    image: hyperledger/besu:22.10.3
    restart: unless-stopped
    container_name: validator4
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys/validator4/key:/opt/besu/key
    network_mode: "host"
    env_file:
      - ./common.env
      - ./bootnodes.env
    environment:
      - BESU_IDENTITY=validator4
      - BESU_MINER_EXTRA_DATA=0x76616c696461746f7234
      - BESU_P2P_PORT=30304
